language: generic
dist: bionic
sudo: false
cache:
  directories:
    - ~/Arduino
    - ~/.arduino15/packages/

# default phases
before_install:
  - mkdir -p "$HOME/bin"
  - curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | BINDIR="$HOME/bin" sh
  - export PATH="$PATH:$HOME/bin"
  - arduino-cli core update-index --additional-urls https://downloads.arduino.cc/packages/package_index.json
  - arduino-cli core update-index --additional-urls https://files.seeedstudio.com/arduino/package_seeeduino_boards_index.json
  - arduino-cli core install arduino:avr --additional-urls https://downloads.arduino.cc/packages/package_index.json
  - arduino-cli core install Seeeduino:samd --additional-urls https://files.seeedstudio.com/arduino/package_seeeduino_boards_index.json
  - |
    installLibrary() {
      local -r repositoryFullName="$1"
      local -r repositoryName="${repositoryFullName##*/}"
      # clone repository to the libraries folder of the Seeed_Arduino_USBDISP
      git clone https://github.com/${repositoryFullName} "${HOME}/Arduino/libraries/${repositoryName}"
      cd "${HOME}/Arduino/libraries/${repositoryName}"
      cd "${TRAVIS_BUILD_DIR}"
    }
  - buildExampleSketch() { arduino-cli compile  --warnings all --fqbn $BOARD $PWD/examples/$1 --verbose; }
  - buildExampleUtilitySketch() { arduino-cli compile --warnings all --fqbn $BOARD $PWD/examples/utility/$1 --verbose; }

install:
  - mkdir -p $HOME/Arduino/libraries

script: 
    - echo "*************************************NullFunctional*********************************************"
    - rm -rf $HOME/Arduino/libraries/*
    - installLibrary Seeed-Studio/Seeed_Arduino_USBDISP
    - export BOARD=Seeeduino:samd:seeed_wio_terminal
    - buildExampleSketch WioTerminal-ADS1115;

    - echo "*************************************USBDisplayAndMouseControl*********************************************"
    - rm -rf $HOME/Arduino/libraries/*
    - installLibrary Seeed-Studio/Seeed_Arduino_USBDISP
    - installLibrary  arduino-libraries/Mouse
    - export BOARD=Seeeduino:samd:seeed_wio_terminal
    - buildExampleSketch WioTerminal_BackLight;

notifications:
  webhooks:
    urls:
      - https://www.travisbuddy.com/
    on_success: never
    on_failure: always
